---
title: "Tidying KNBS Data"
author: "Brian Githinji"
date: "24/02/2020"
output: github_document
---



```{r load libraries}
library(tidyverse)
library(tabulizer)
```

```{r File Locations}
file_location <- "./census reports/VOLUME 1 KPHC 2019.pdf"
file_location1 <- "./census reports/VOLUME IV KPHC 2019.pdf"
```


```{r eval=F}
# Extract table on page
# note that this launches an interactive page so that you can select the area of the table to be scrapped.
population_sex_county <- extract_areas(file = file_location, pages = 17, guess = FALSE)

# population_by_sex_county <- extract_areas(file = file_location, pages = 17, guess = FALSE)
```

```{r, eval=F}
# convert to a data.frame
population_by_sex_county <- as.data.frame(population_sex_county[[1]])

# remove the endless ....
population_by_sex_county$V1 <- str_replace(string = population_by_sex_county$V1, pattern = "\\.{2,}", replacement = ";")

population_by_sex_county <- separate(data = population_by_sex_county, col = V1, into = c("County","Male"), sep = ";")

population_by_sex_county$Male <- str_trim(string = population_by_sex_county$Male, side = "both")

population_by_sex_county <- population_by_sex_county %>% 
                            filter(!is.na(Male)) %>% 
                            select(-V2) %>% 
                            rename(Female = V3, Intersex = V4, Total = V5)

```


```{r, eval=F}
# write to csv

write_csv(x = population_by_sex_county, path = ".\\tidy data\\population_by_sex_county.csv")
```

# Volume IV Data
### Population Level of Education Data

```{r}
pages <- c(57:87)
population_school <- extract_tables(file = file_location1, pages = pages)
```

```{r}
# remove the 1:5 rows of each of the list elements
population_school_df <- map_df(.x = population_school, .f = ~slice(as.data.frame(.x, stringsAsFactors = F), -c(1:5)))

# get the column names
column_names <- population_school[[1]] %>% .[3,]
column_names[8] <- "adult_basic_education"
column_names[6] <- "tvet"

# set the column names and tidy the case
names(population_school_df) <- column_names
population_school_df <- janitor::clean_names(population_school_df)

# replace all the dashes which represent missing values with NA
population_school_df <- map_df(.x = population_school_df, ~str_replace(string = ., pattern = "-", NA_character_)) 
```

Next steps would be to scrape the reference table of the counties and subcounties so that one can use joins to separate the counties and sub-counties

```{r eval=F}
# Save the data set for now
write_csv(x = population_school_df, path = ".\\tidy data\\t2.3_population_currently_attending_school.csv")
```

## Mobile Ownership Population Data

```{r}
pages <- c(438:444)
population_mobile_ownership <- extract_tables(file = file_location1, pages = pages)
```

```{r}
population_mobile_ownership_df <- map_df(.x = population_mobile_ownership, .f = ~slice(as.data.frame(.x, stringsAsFactors = F), -c(1,2)))
# the first two rows have additional white space. Remove the additional white space
population_mobile_ownership_df$V2 <- str_replace(string = population_mobile_ownership_df$V2, pattern = "\\s{2}", replacement = "" )
# split the column
population_mobile_ownership_df <- separate(population_mobile_ownership_df, col = V2, into = c("Total","Male","Female"), sep = " ")
# split the column
population_mobile_ownership_df <- separate(population_mobile_ownership_df, col = V5, into = c("male2","per_cent"), sep = "\\s")
#column names
population_mobile_ownership_df <- rename(population_mobile_ownership_df, "county/sub-county" = V1, "total2" = V3, 
                                         "per_cent_total" = V4, "per_cent_male" = `per_cent`, "female2" = V6, 
                                         "per_cent_female" = V7)

```

```{r, eval=F}
write_csv(x = population_mobile_ownership_df, path = ".\\tidy data\\t2.32_population_mobile_ownership.csv")
```


```{r eval=FALSE}
# Convert from wide to long
column_names <- colnames(population_mobile_ownership_df)
column_names[2:4] <- glue::glue("{column_names[2:4]}-1")
column_names <- str_replace(column_names, "2", "")
column_names[5:10] <- glue::glue("{column_names[5:10]}-2")
colnames(population_mobile_ownership_df) <-  column_names
population_mobile_ownership_df_long <- pivot_longer(population_mobile_ownership_df, cols = 2:10, 
                                                    names_to = c("population","mobile_ownership"), 
                                                    names_pattern = "(.*)-(\\d)")
```

### COnventional Asses Ownership Population Data

```{r}
pages <- c(475:481)
population_conventional_ownership <- extract_tables(file = file_location1, pages = pages)
```

```{r}
population_conventional_ownership_df <- map_df(.x = population_conventional_ownership, .f = ~slice(as.data.frame(.x, stringsAsFactors = F), -c(1:4)))

# split the column
population_conventional_ownership_df <- separate(population_conventional_ownership_df, col = V6, into = c("atv","internet","bicycle"), sep = " ")

#column names
population_conventional_ownership_df <- rename(population_conventional_ownership_df, "county/sub-county" = V1, 
                                               "households" = V2, 
                                         "radio" = V3, "laptop_tablet" = V4, "ftv" = V5, 
                                         "motor_cycle" = V7, "refrigerator" = V8, "car" = V9, 
                                         "truck/lorry/bus/three_wheeler" = V10, "tuk_tuk" = V11)
```

```{r}
write_csv(x = population_conventional_ownership_df, path = ".\\tidy data\\t2.36_population_household_assets.csv")
```

### Cooking Fuel Population Data

```{r}
pages <- c(343:350)
population_cooking_fuel <- extract_tables(file = file_location1, pages = pages)
```


```{r}
population_cooking_fuel_df <- map_df(.x = population_cooking_fuel, 
                                     .f = ~slice(as.data.frame(.x, stringsAsFactors = F), -c(1:5)))
# Get the column names
column_names <- population_cooking_fuel[[1]][5,]
column_names[1:2] <- c("county", "households")
column_names[5] <- ("lpg_biogas_firewood")
column_names[8] <- "not_stated"
population_cooking_fuel_df<- `colnames<-`(population_cooking_fuel_df, column_names)

# split the column
population_cooking_fuel_df <- separate(population_cooking_fuel_df, col = lpg_biogas_firewood, into = c("lpg","biogas","firewood"), sep = " ")

```

```{r}
write_csv(x = population_cooking_fuel_df, path = ".\\tidy data\\t2.18_population_cooking_fuel.csv")
```


### County & Sub-COunty Reference Table

```{r}
pages <- c(20:22)
reference_table <- extract_tables(file = file_location1, pages = pages)
```


```{r}
# get column names
column_names <- c("county_code", "county_name", "sub-county_code","sub-county_name")

# tidy the data
reference_table_df1 <- map_df(.x = reference_table, 
                                     .f = ~slice(as.data.frame(.x, stringsAsFactors = F), -c(1:2)) %>% 
                               select(1:4))
reference_table_df2 <- map_df(.x = reference_table, 
                                     .f = ~slice(as.data.frame(.x, stringsAsFactors = F), -c(1:2)) %>% 
                               select(5:8))

reference_table_df1<- `colnames<-`(reference_table_df1, column_names)
reference_table_df2<- `colnames<-`(reference_table_df2, column_names)

reference_table_df <- bind_rows(reference_table_df1, reference_table_df2)
```

```{r}
write_csv(x = reference_table_df, path = ".\\tidy data\\t1.9_counties_and_sub-counties.csv")
```



